version: 2
jobs:
  build:
    docker:
      - image: circleci/node:stretch
      - image: couchdb:2.3.0
    steps:
      - checkout
      - run:
          name: Install Deno
          command: |
            curl -fsSL https://deno.land/x/install/install.sh | bash -s -- v0.13.0
      - run:
          name: Run Tests
          command: |
            export PATH=$HOME/.deno/bin:$PATH
            sleep 5
            deno -A couch_test.ts